### ISSUE TITLE
PCKs exported from 4.4-dev5 and newer aren't read correctly

### ISSUE THREAD

**Issue by Winonamac** [GDRETools/gdsdecomp#236]
### System information

Windows 11

### Issue description

Somewhere between [Godot 4.4-dev4](https://github.com/godotengine/godot/commit/36e6207bb48fafd43b98a458d0c461ad982b4e68) and [Godot 4.4-dev5](https://github.com/godotengine/godot/commit/9e6098432aac35bae42c9089a29ba2a80320d823) some change was made to the PCK format that made GDRE unable to extract files from it properly.

### Steps to reproduce

1. Create or open a project in Godot 4.4-dev5
2. Export said project
3. Attempt to recover it using Godot RE Tools, v0.8.0

### Recovery log

```
GDRE Tools v0.8.0
Windows 10.0.22631, NVIDIA GeForce RTX 3060, opengl3
At least one error was detected while extracting pack!
.godot/exported/133200997/export-3070c538c03ee49b7677ff960a3f5195-main.scn(12)
.godot/global_script_class_cache.cfg(12)
.godot/imported/icon.svg-218a8f2b3041327d8a5756f3a245f83b.ctex(12)
.godot/uid_cache.bin(12)
icon.svg(12)
icon.svg.import(12)
main.tscn.remap(12)
project.binary(12)
secret.txt(12)

WARNING: Converting lossy imports, you may lose fidelity for indicated assets when re-importing upon loading the project
   at: ImportExporter::_export_imports (modules\gdsdecomp\utility\import_exporter.cpp:181)
WARNING: No import files found!
   at: ImportExporter::_export_imports (modules\gdsdecomp\utility\import_exporter.cpp:186)
```

### Link to game download

[test-project.zip](https://github.com/user-attachments/files/18255173/test-project.zip)

**Comment by nikitalita** [comment]
I need the actual pck to test it.

**Comment by Winonamac** [comment]
My apologies. I forgot to include it in the zip.

Exported from 4.4-dev7
[test.zip](https://github.com/user-attachments/files/18266795/test.zip)

**Comment by nikitalita** [comment]
I found the issue. They started trimming the `res://` prefix from the paths in PCK files. When the build job is done, try the standalone artifacts here: https://github.com/GDRETools/gdsdecomp/actions/runs/12530048823?pr=238

**Comment by Winonamac** [comment]
That seems to have been it. Everything is able to be recovered properly from the pck now
